import {
    AlertTriangle,
    ArrowDown,
    ArrowRight,
    ArrowUp,
    ArrowUpRight,
    BarChart3,
    Bell,
    Bookmark,
    Building2,
    Calendar,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ClipboardCheck,
    Clock,
    Code,
    Copy,
    Cpu,
    CreditCard,
    DollarSign,
    Download,
    Droplet,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileCheck,
    Filter,
    Fingerprint,
    Flag,
    Flame,
    Gift,
    Globe,
    Grid3x3,
    Hash,
    Headset,
    History,
    Home,
    Inbox,
    Info,
    Key,
    Layers,
    LayoutDashboard,
    Link2,
    List,
    Loader2,
    Lock,
    LogOut,
    type LucideIcon,
    type LucideProps,
    Mail,
    MapPin,
    Menu,
    Mic,
    Minus,
    Moon,
    MoreVertical,
    Pencil,
    Percent,
    Phone,
    Plus,
    Receipt,
    RefreshCw,
    Search,
    Send,
    Settings,
    Shield,
    ShieldCheck,
    Signal,
    Smartphone,
    Sparkles,
    Star,
    Sun,
    Ticket,
    Trash2,
    TrendingDown,
    TrendingUp,
    Tv,
    Upload,
    User,
    Users,
    Wallet,
    Webhook,
    Wifi,
    X,
    XCircle,
    Zap,
} from 'lucide-react';

/**
 * Maps the Tappy design-system icon names to lucide-react components so screens
 * and the shell can use `<Icon name="wallet" />` exactly like the prototype.
 */
const ICON_MAP = {
    dashboard: LayoutDashboard,
    phone: Phone,
    signal: Signal,
    gift: Gift,
    zap: Zap,
    bolt: Zap,
    layers: Layers,
    users: Users,
    user: User,
    wallet: Wallet,
    receipt: Receipt,
    chart: BarChart3,
    code: Code,
    key: Key,
    webhook: Webhook,
    shield: Shield,
    shieldcheck: ShieldCheck,
    settings: Settings,
    headset: Headset,
    home: Home,
    building: Building2,
    globe: Globe,
    list: List,
    flag: Flag,
    audit: ClipboardCheck,
    percent: Percent,
    search: Search,
    bell: Bell,
    plus: Plus,
    minus: Minus,
    check: Check,
    checkcircle: CheckCircle2,
    x: X,
    xcircle: XCircle,
    alert: AlertTriangle,
    info: Info,
    clock: Clock,
    chevdown: ChevronDown,
    chevright: ChevronRight,
    chevleft: ChevronLeft,
    chevup: ChevronUp,
    arrowright: ArrowRight,
    arrowup: ArrowUp,
    arrowdown: ArrowDown,
    arrowupright: ArrowUpRight,
    trendup: TrendingUp,
    trenddown: TrendingDown,
    copy: Copy,
    download: Download,
    upload: Upload,
    refresh: RefreshCw,
    trash: Trash2,
    eye: Eye,
    eyeoff: EyeOff,
    moon: Moon,
    sun: Sun,
    filter: Filter,
    more: MoreVertical,
    edit: Pencil,
    menu: Menu,
    logout: LogOut,
    file: File,
    filecheck: FileCheck,
    mail: Mail,
    lock: Lock,
    card: CreditCard,
    calendar: Calendar,
    star: Star,
    bookmark: Bookmark,
    send: Send,
    hash: Hash,
    droplet: Droplet,
    tv: Tv,
    wifi: Wifi,
    flame: Flame,
    sparkles: Sparkles,
    external: ExternalLink,
    dollar: DollarSign,
    loader: Loader2,
    inbox: Inbox,
    ticket: Ticket,
    link: Link2,
    fingerprint: Fingerprint,
    device: Smartphone,
    cpu: Cpu,
    grid: Grid3x3,
    pin: MapPin,
    history: History,
    mic: Mic,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_MAP;

interface IconProps extends Omit<LucideProps, 'ref'> {
    /** Tappy design-system icon name. */
    name?: IconName;
    /** Direct lucide component (legacy API used by nav helpers). */
    iconNode?: LucideIcon | null;
}

export function Icon({ name, iconNode, ...props }: IconProps) {
    const Component = iconNode ?? (name ? ICON_MAP[name] : null);

    if (!Component) {
        return null;
    }

    return <Component {...props} />;
}
